### ISSUE TITLE
java.lang.NoClassDefFoundError: for com.github.luben.zstd.ZstdInputStream   

### ISSUE THREAD

**Issue by hegdemahendra** [luben/zstd-jni#111]
Hi,

In my application (maven app) I am using ‘net.iakovlev.timeshape’ library which is dependent on  ‘zstd-jni-1.3.7-1.jar’ internally.

My application works fine in local machine, but when I deploy it to server it gives below error - 

 

————————————————————————————————

java.lang.NoClassDefFoundError: com/github/luben/zstd/ZstdInputStream

                at net.iakovlev.timeshape.TimeZoneEngine.initialize(TimeZoneEngine.java:129)

                at net.iakovlev.timeshape.TimeZoneEngine.initialize(TimeZoneEngine.java:116)

                at dtap.service.TimezoneService.<init>(TimezoneService.java:18)

                at functions.processors.KernelIntgrationProcessor.processElement(KernelIntgrationProcessor.java:49)

                at functions.processors.KernelIntgrationProcessor.processElement(KernelIntgrationProcessor.java:25)

                at org.apache.flink.streaming.api.operators.ProcessOperator.processElement(ProcessOperator.java:66)

                at org.apache.flink.streaming.runtime.io.StreamInputProcessor.processInput(StreamInputProcessor.java:202)

                at org.apache.flink.streaming.runtime.tasks.OneInputStreamTask.run(OneInputStreamTask.java:105)

                at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:300)

                at org.apache.flink.runtime.taskmanager.Task.run(Task.java:704)

                at java.lang.Thread.run(Thread.java:748)

Caused by: java.lang.ClassNotFoundException: com.github.luben.zstd.ZstdInputStream

                at java.net.URLClassLoader.findClass(URLClassLoader.java:382)

                at java.lang.ClassLoader.loadClass(ClassLoader.java:424)

                at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)

                at java.lang.ClassLoader.loadClass(ClassLoader.java:357)

                ... 11 more

————————————————————————————————

 

I unzipped the deployed jar and I could find the class (com.github.luben.zstd.ZstdInputStream) file present there.

I directly copied the jar ‘zstd-jni-1.3.7-1.jar’ to /lib directory of the server where I have deployed the application.

 

Then it worked in some server and in some other server started getting below error -

 

java.lang.NoClassDefFoundError: Could not initialize class com.github.luben.zstd.ZstdInputStream

                at org.apache.commons.compress.compressors.zstandard.ZstdCompressorInputStream.<init>(ZstdCompressorInputStream.java:43)

                at net.iakovlev.timeshape.TimeZoneEngine.initialize(TimeZoneEngine.java:129)

                at net.iakovlev.timeshape.TimeZoneEngine.initialize(TimeZoneEngine.java:116)

                at dtap.service.TimezoneService.<init>(TimezoneService.java:18)

                at functions.processors.KernelIntgrationProcessor.processElement(KernelIntgrationProcessor.java:49)

                at functions.processors.KernelIntgrationProcessor.processElement(KernelIntgrationProcessor.java:25)

                at org.apache.flink.streaming.api.operators.ProcessOperator.processElement(ProcessOperator.java:66)

                at org.apache.flink.streaming.runtime.io.StreamInputProcessor.processInput(StreamInputProcessor.java:202)

                at org.apache.flink.streaming.runtime.tasks.OneInputStreamTask.run(OneInputStreamTask.java:105)

                at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:300)

                at org.apache.flink.runtime.taskmanager.Task.run(Task.java:704)

                at java.lang.Thread.run(Thread.java:748)

What could be the issue? Could anyone help me with the possible solution?

Thanks
Mahendra

**Comment by luben** [comment]
Hmm, that's strange. Any chance the failing server has quite outdated glibc, using musle or another libc?

Another thing you can do to help debugging the issue is just create yourself an instance of `ZstdInputStream` and see what happens.

**Comment by hegdemahendra** [comment]
Thanks for the reply Luben.

I am using openJDK :

openjdk version "1.8.0_222"

OpenJDK Runtime Environment (build 1.8.0_222-b10)

OpenJDK 64-Bit Server VM (build 25.222-b10, mixed mode)

As you suggested, tried creating instance of ZstdInputStream in my code, there also I am getting same below error -

 

java.lang.NoClassDefFoundError: Could not initialize class com.github.luben.zstd.ZstdInputStream

                at functions.processors.DecodedFordDataProcessor.processElement(DecodedFordDataProcessor.java:65)

                at functions.processors.DecodedFordDataProcessor.processElement(DecodedFordDataProcessor.java:32)

                at org.apache.flink.streaming.api.operators.ProcessOperator.processElement(ProcessOperator.java:66)

                at org.apache.flink.streaming.runtime.io.StreamInputProcessor.processInput(StreamInputProcessor.java:202)

                at org.apache.flink.streaming.runtime.tasks.OneInputStreamTask.run(OneInputStreamTask.java:105)

                at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:300)

                at org.apache.flink.runtime.taskmanager.Task.run(Task.java:704)

                at java.lang.Thread.run(Thread.java:748)

**Comment by luben** [comment]
Hmm, that's strange. I have no idea why it's happening. If I remember correctly, Flink was using separate class loaders for each task. Could this be causing the trouble?

**Comment by luben** [comment]
@hegdemahendra , any chance it's related to the use of per-task ClassLoaders in Flink?

**Comment by luben** [comment]
Any progress?

**Comment by luben** [comment]
closing for inactivity

**Comment by mojirml** [comment]
I also encountered this problem. On the remote server, the local is OK, but the remote error report is very confused
java.lang.NoClassDefFoundError: com/github/luben/zstd/ZstdCompressCtx

**Comment by zjdznl** [comment]
FYI，I got this problem，because my project's dependency is conflict with spark.
use `maven-shade-plugin` is a way to solve it.

**Comment by JJ-JOKER** [comment]
i solve this problem , you can check your pom , someone may include zstd-jni, just exclude it
