### ISSUE TITLE
[ Help ] ZStd Stream Large File

### ISSUE THREAD

**Issue by Sundarcj** [luben/zstd-jni#118]
Hi ,
I am new to ZStd( even compresssion domain :anxious ) Could anyone give sample Java code for compress large data ( InputStream ) in  Zstd. I tired with apache common and it throws 

`Exception in thread "main" java.lang.NoClassDefFoundError: com/github/luben/zstd/ZstdOutputStream
	at org.apache.commons.compress.compressors.zstandard.ZstdCompressorOutputStream.<init>(ZstdCompressorOutputStream.java:83)
	at com.zoho.test.testzstd.main(testzstd.java:28)
Caused by: java.lang.ClassNotFoundException: com.github.luben.zstd.ZstdOutputStream
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 2 more
`

Thanks in advance

**Comment by luben** [comment]
I think Zstd-jni is optional dependency of apache commons, so try to declare it as dependency.
