### ISSUE TITLE
Native library loading error

### ISSUE THREAD

**Issue by mchv** [luben/zstd-jni#12]
Following update to `1.0.0` I still see an error like on `0.8.0` (see #9 for details)
```
[info] Exception encountered when attempting to run a suite with class name: com.gu.contentapi.porter.integration.flexible.ZstdCompressionTest *** ABORTED ***
[info]   java.lang.UnsatisfiedLinkError: com.github.luben.zstd.ZstdOutputStream.recommendedCOutSize()J
[info]   at com.github.luben.zstd.ZstdOutputStream.recommendedCOutSize(Native Method)
[info]   at com.github.luben.zstd.ZstdOutputStream.<clinit>(ZstdOutputStream.java:29)
[info]   at com.gu.contentapi.porter.integration.ZstdCompression$.compress(Compression.scala:51)
[info]   at com.gu.contentapi.porter.integration.flexible.ZstdCompressionTest$$anonfun$1.apply$mcV$sp(ZstdCompressionTests.scala:12)
[info]   at com.gu.contentapi.porter.integration.flexible.ZstdCompressionTest$$anonfun$1.apply(ZstdCompressionTests.scala:10)
[info]   at com.gu.contentapi.porter.integration.flexible.ZstdCompressionTest$$anonfun$1.apply(ZstdCompressionTests.scala:10)
[info]   at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22)
[info]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
```

**Comment by mchv** [comment]
I will try tomorrow to test with a version published locally.

**Comment by luben** [comment]
Thanks for opening the issue. I will look again what may be the difference. I am using travis-ci to build the mac os native object: https://travis-ci.org/luben/zstd-jni/jobs/157779438

BTW, if a local build works, can you give me the output of:

```
~/zstd-jni(branch:master) » ls -Rl target/classes
```

to see what may be the difference.

Thanks in advance helping me debug it.

**Comment by luben** [comment]
I think I found the problem - I was packaging a older version of the dylib. Fixing it now and will re-upload the release shortly

**Comment by luben** [comment]
pushed to maven, can you test it, it will land on the index in 2-3 hours.

**Comment by mchv** [comment]
@luben thanks, I have just tested it (adding `changing()`to my dependency in `sbt` to redownload the jar) and it works fine now 👍 
```
[info] ZstdCompressionTest:
[info] - zstd should compress the content
[info] - ztsd and then unzstd should return the same content 
```
