### ISSUE TITLE
Native Library Loading Issue

### ISSUE THREAD

**Issue by DEVILCODER-SB99** [luben/zstd-jni#125]
Caused by: java.security.AccessControlException: access denied ("java.lang.RuntimePermission" "loadLibrary.zstd-jni")
        at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472) ~[?:?]
        at java.security.AccessController.checkPermission(AccessController.java:1036) ~[?:?]
        at java.lang.SecurityManager.checkPermission(SecurityManager.java:408) ~[?:?]
        at java.lang.SecurityManager.checkLink(SecurityManager.java:694) ~[?:?]
        at java.lang.Runtime.loadLibrary0(Runtime.java:801) ~[?:?]
        at java.lang.System.loadLibrary(System.java:1907) ~[?:?]
        at com.github.luben.zstd.Native.load(Native.java:62) ~[lucene-core-8.5.1.jar:8.5.1-SNAPSHOT unknown - senky - 2020-06-26 10:37:44]

when i run me getting this error. can u please explain why i am getting this...i m stuck on it from last 48 hours

**Comment by DEVILCODER-SB99** [comment]
I forget to gave permission in security policy of jdk

**Comment by praveennish** [comment]
Hi @DEVILCODER-SB99 and @luben  Does it mean that all machine needs to add security policy specifically for folder contain libzstd so file ?
