### ISSUE TITLE
Help understanding "Version not supported" when reading zstd files in EMR 6

### ISSUE THREAD

**Issue by alvarotuso** [luben/zstd-jni#152]
We are running into this error while reading zstd files in spark:
```
ava.io.IOException: Decompression error: Version not supported
	at com.github.luben.zstd.ZstdInputStream.readInternal(ZstdInputStream.java:164)
	at com.github.luben.zstd.ZstdInputStream.read(ZstdInputStream.java:120)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
	at java.io.ObjectInputStream$PeekInputStream.read(ObjectInputStream.java:2781)
	at java.io.ObjectInputStream$PeekInputStream.readFully(ObjectInputStream.java:2797)
	at java.io.ObjectInputStream$BlockDataInputStream.readShort(ObjectInputStream.java:3274)
	at java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:934)
	at java.io.ObjectInputStream.<init>(ObjectInputStream.java:396)
	at org.apache.spark.MapOutputTracker$.deserializeObject$1(MapOutputTracker.scala:954)
	at org.apache.spark.MapOutputTracker$.deserializeMapStatuses(MapOutputTracker.scala:964)
	at org.apache.spark.MapOutputTrackerWorker.$anonfun$getStatuses$2(MapOutputTracker.scala:856)
	at org.apache.spark.util.KeyLock.withLock(KeyLock.scala:64)
	at org.apache.spark.MapOutputTrackerWorker.getStatuses(MapOutputTracker.scala:851)
	at org.apache.spark.MapOutputTrackerWorker.getMapSizesByExecutorId(MapOutputTracker.scala:808)
	at org.apache.spark.shuffle.sort.SortShuffleManager.getReader(SortShuffleManager.scala:128)
	at org.apache.spark.sql.execution.ShuffledRowRDD.compute(ShuffledRowRDD.scala:185)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:349)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:313)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:349)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:313)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:349)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:313)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:349)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:313)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:349)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:313)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:127)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:446)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1377)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:449)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
Taking a look at the code, it would seem like we are hitting this error: https://github.com/luben/zstd-jni/blob/3d16e515253a0b6941810ab3ee4055201ca9ff54/src/main/native/legacy/zstd_legacy.h#L350

However the files are being written independently with https://github.com/luben/zstd-jni/releases/tag/v1.3.7-3 and `zstandard==0.11.1` (python) and they're read correctly when using `v1.3.7-3`

What does this error mean? Is there some version associated with the file format itself latest versions don't support?

**Comment by luben** [comment]
Which version are you using?

**Comment by alvarotuso** [comment]
EMR 6 (https://docs.aws.amazon.com/emr/latest/ReleaseGuide/emr-release-6x.html) uses `hadoop==3.2.1` which seems to be using `com.github.luben:zstd-jni:1.4.3-1` https://github.com/apache/hadoop/blob/fb79be932c28a67ed01576252f44eae072fef7f0/LICENSE-binary#L367
I'm not entirely clear if AWS has their own internal fork though

One interesting point is that the cluster seems to be able to read the files, but fails with that error if we try to apply a `repartition` in spark over them

It might be pretty tough to figure out but maybe you had some pointers on what this could mean?

**Comment by luben** [comment]
No idea, the message comes from the native library. It is strange that it's able to read them but `repartition` breaks it. I don't know what may be the issue.

**Comment by alvarotuso** [comment]
No worries, thanks for looking into it!

**Comment by JonathanAquino** [comment]
We worked around this by reading in the zstd csv, writing it as parquet, then reading the parquet. Then repartition works.

**Comment by kushagra391** [comment]
seems its related to https://stackoverflow.com/questions/64876463/spark-3-0-1-tasks-are-failing-when-using-zstd-compression-codec

for EMR > 6.0, we need to add to include following to cluster configuration. It can not be overridden from job config 
```json
   {
      "classification":"spark-defaults",
      "properties":{
         "spark.shuffle.mapStatus.compression.codec":"lz4"
      }
   },
```

cc: @alvarotuso @JonathanAquino

**Comment by alvarotuso** [comment]
Nice!
