### ISSUE TITLE
Architecture classified jar for linux/amd64 does not have the right name for libzstd-jni-1.4.9-5.so

### ISSUE THREAD

**Issue by sanjay-90210** [luben/zstd-jni#173]
Architecture classified jar as found [here](https://repo1.maven.org/maven2/com/github/luben/zstd-jni/1.4.9-5/zstd-jni-1.4.9-5-linux_amd64.jar) has the .so name wrong and so running an application with such a jar runs into errors.

```
./bin/run.sh data.json 
Exception in thread "main" java.lang.UnsatisfiedLinkError: no zstd-jni-1.4.9-5 in java.library.path
Unsupported OS/arch, cannot find /linux/amd64/libzstd-jni-1.4.9-5.so or load zstd-jni-1.4.9-5 from system libraries. Please try building from source the jar or providing libzstd-jni-1.4.9-5 in your system.
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1860)
	at java.lang.Runtime.loadLibrary0(Runtime.java:871)
	at java.lang.System.loadLibrary(System.java:1124)
	at com.github.luben.zstd.util.Native.load(Native.java:87)
	at com.github.luben.zstd.util.Native.load(Native.java:55)
	at com.github.luben.zstd.Zstd.<clinit>(Zstd.java:13)

```
The jar does not have the .so with the **jni** portion.

```
jar -tvf zstd-jni-1.4.9-5-linux_amd64.jar 
   328 Wed Apr 14 18:46:24 IST 2021 META-INF/MANIFEST.MF
     0 Wed Apr 14 18:46:24 IST 2021 com/
     0 Wed Apr 14 18:46:24 IST 2021 com/github/
     0 Wed Apr 14 18:46:24 IST 2021 com/github/luben/
     0 Wed Apr 14 18:46:24 IST 2021 com/github/luben/zstd/
     0 Wed Apr 14 18:46:24 IST 2021 com/github/luben/zstd/util/
     0 Wed Apr 14 18:46:24 IST 2021 linux/
     0 Wed Apr 14 18:46:24 IST 2021 linux/amd64/
959796 Wed Apr 14 15:18:06 IST 2021 linux/amd64/libzstd-1.4.9-5.so
  5110 Wed Apr 14 15:01:16 IST 2021 com/github/luben/zstd/ZstdInputStreamNoFinalizer.class
  2240 Wed Apr 14 15:01:16 IST 2021 com/github/luben/zstd/ZstdDictTrainer.class
  1112 Wed Apr 14 15:01:16 IST 2021 com/github/luben/zstd/ZstdDictCompress.class
  4609 Wed Apr 14 15:01:16 IST 2021 com/github/luben/zstd/ZstdDirectBufferCompressingStream.class

```
The fat jar with all the .so files has the name right as **libzstd-jni-1.4.9-5.so** and so works fine.

**Comment by luben** [comment]
Hmm, right. The classified jars have the native part under wrong names. I am preparing v1.5.0 and it I will fix also this problem.

**Comment by luben** [comment]
Fixed in https://github.com/luben/zstd-jni/commit/9a163eebd653977249965044353489529f8c9314

**Comment by luben** [comment]
just pushed v1.5.0-1 with the fix
