### ISSUE TITLE
NullPointerException while using larger block size >= 128kb 

### ISSUE THREAD

**Issue by praveennish** [luben/zstd-jni#185]
I am integrating ZStandard to apache lucene. Multithreaded benchmark works well for existing lz4 and zlib. While running ZStandard implementation, I am seeing NullPointerException in running multithreaded benchmark with 128 kb & 256 kb block while ZStandard with 48kb and 60kb blocks works well. Is there issue with multiple threads or larger block (> 60 kb) ?

Exception in thread "ParallelTaskThread-39" java.lang.RuntimeException: java.lang.NullPointerException
        at org.apache.lucene.benchmark.byTask.tasks.TaskSequence$ParallelTask.run(TaskSequence.java:318)
Caused by: java.lang.NullPointerException
        at org.apache.lucene.document.DocumentStoredFieldVisitor.longField(DocumentStoredFieldVisitor.java:86)
        at org.apache.lucene.codecs.lucene90.compressing.Lucene90CompressingStoredFieldsReader.readField(Lucene90CompressingStoredFieldsReader.java:261)
        at org.apache.lucene.codecs.lucene90.compressing.Lucene90CompressingStoredFieldsReader.visitDocument(Lucene90CompressingStoredFieldsReader.java:676)
        at org.apache.lucene.index.CodecReader.document(CodecReader.java:89)
        at org.apache.lucene.index.BaseCompositeReader.document(BaseCompositeReader.java:173)
        at org.apache.lucene.index.IndexReader.document(IndexReader.java:389)
        at org.apache.lucene.benchmark.byTask.tasks.ReadTask.doLogic(ReadTask.java:132)
        at org.apache.lucene.benchmark.byTask.tasks.PerfTask.runAndMaybeStats(PerfTask.java:132)
        at org.apache.lucene.benchmark.byTask.tasks.TaskSequence.doSerialTasks(TaskSequence.java:189)
        at org.apache.lucene.benchmark.byTask.tasks.TaskSequence.doLogic(TaskSequence.java:127)
        at org.apache.lucene.benchmark.byTask.tasks.PerfTask.runAndMaybeStats(PerfTask.java:143)
        at org.apache.lucene.benchmark.byTask.tasks.TaskSequence$ParallelTask.run(TaskSequence.java:308)

Above exception is generated while reading a field(for e.g. longField above but happens with all field types string, int, byte, etc), but the problem lies while writing these fields on a bigger block size(128 & 256 kb)

**Comment by luben** [comment]
Hi @praveennish,

Sorry for the late reply. I somehow missed this issue.

I don't know about any issues currently with multi-threading. There are a lot of things unclear in the above description - what is a "block"? How are you compressing/decompressing the blocks?
Please note that compression and decompression context are not thread safe - you cannot use one context from multiple threads. If you are doing this I suggest creating a thread-local instance and using it.

Did you manage to find solution in the meantime?

**Comment by praveennish** [comment]
closing this as this is not related to this library set up
