### ISSUE TITLE
UnsatisfiedLinkError

### ISSUE THREAD

**Issue by hswhsw610** [luben/zstd-jni#189]
java.lang.UnsatisfiedLinkError: 'void net.midnightmc.zstd.ZstdCompressCtx.init()'
	at net.midnightmc.zstd.ZstdCompressCtx.init(Native Method) ~[MidnightCore-1.0-all.jar:?]
	at net.midnightmc.zstd.ZstdCompressCtx.<init>(ZstdCompressCtx.java:28) ~[MidnightCore-1.0-all.jar:?]
	at net.midnightmc.zstd.Zstd.compress(Zstd.java:786) ~[MidnightCore-1.0-all.jar:?]
	at net.midnightmc.zstd.Zstd.compress(Zstd.java:775) ~[MidnightCore-1.0-all.jar:?]
	at net.midnightmc.core.api.MapAPI.lambda$saveWorldToDB$1(MapAPI.java:120) ~[MidnightCore-1.0-all.jar:?]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper.jar:git-Paper-196]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [paper.jar:git-Paper-196]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) [paper.jar:git-Paper-196]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
	at java.lang.Thread.run(Thread.java:831) [?:?]

using gradle with relocate

**Comment by daniel-sudz** [comment]
@hswhsw610 similar problem on maven with shading #188 . Have you found a resolution?  

I'm currently finding that renaming just the Native class from utils to anything else does the trick to avoid classpath pollution but I don't know why it works and it does not make a lot of sense to me.

**Comment by daniel-sudz** [comment]
I figured out the issue but I don't know what the proper solution is. 

@hswhsw610 what happens is that when you shade/relocate/whatever this only affects the java bytecode. The native files which reference the java files do not get affected as the renaming utilities have no knowledge of them.

**Comment by luben** [comment]
Yes, just relocating the classes does not affect the native part that has the old fqclass in the native function/method names.

I am also aware of the Hadoop issues with the conflicting jar.

Unfortunately I don’t have solution for any of the above issues. If somebody has any idea how we can improve I am open to suggestions.
