### ISSUE TITLE
Caused by: java.lang.UnsatisfiedLinkError: no zstd-jni in java.library.path

### ISSUE THREAD

**Issue by rengaa30** [luben/zstd-jni#190]
Hi,
       We are getting the following error messages and we verified that the libzstd-jni.so file exists. Could you help us to resolve this issue.

Caused by: org.apache.kafka.common.KafkaException: java.lang.UnsatisfiedLinkError: no zstd-jni in java.library.path
Unsupported OS/arch, cannot find /linux/amd64/libzstd-jni.so or load zstd-jni from system libraries. Please try building from source the jar or providing libzstd-jni in your system.
        at org.apache.kafka.common.record.CompressionType$5.wrapForInput(CompressionType.java:133)
        at org.apache.kafka.common.record.DefaultRecordBatch.compressedIterator(DefaultRecordBatch.java:261)
        at org.apache.kafka.common.record.DefaultRecordBatch.streamingIterator(DefaultRecordBatch.java:346)
        at org.apache.kafka.clients.consumer.internals.Fetcher$CompletedFetch.nextFetchedRecord(Fetcher.java:1496)
        at org.apache.kafka.clients.consumer.internals.Fetcher$CompletedFetch.fetchRecords(Fetcher.java:1533)
        at org.apache.kafka.clients.consumer.internals.Fetcher$CompletedFetch.access$1700(Fetcher.java:1374)
        at org.apache.kafka.clients.consumer.internals.Fetcher.fetchRecords(Fetcher.java:676)
        at org.apache.kafka.clients.consumer.internals.Fetcher.fetchedRecords(Fetcher.java:631)
        at org.apache.kafka.clients.consumer.KafkaConsumer.pollForFetches(KafkaConsumer.java:1313)
        ... 8 more
Caused by: java.lang.UnsatisfiedLinkError: no zstd-jni in java.library.path
Unsupported OS/arch, cannot find /linux/amd64/libzstd-jni.so or load zstd-jni from system libraries. Please try building from source the jar or providing libzstd-jni in your system.
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1865)
        at java.lang.Runtime.loadLibrary0(Runtime.java:870)
        at java.lang.System.loadLibrary(System.java:1122)
        at com.github.luben.zstd.util.Native.load(Native.java:108)
        at com.github.luben.zstd.util.Native.load(Native.java:60)
        at com.github.luben.zstd.ZstdInputStream.<clinit>(ZstdInputStream.java:21)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at org.apache.kafka.common.record.CompressionType.findConstructor(CompressionType.java:226)
        at org.apache.kafka.common.record.CompressionType.access$100(CompressionType.java:37)
        at org.apache.kafka.common.record.CompressionType$ZstdConstructors.<clinit>(CompressionType.java:218)
        at org.apache.kafka.common.record.CompressionType$5.wrapForInput(CompressionType.java:131)
        ... 16 more

**Comment by luben** [comment]
Any chance you have a mix of old/new versions of zstd-jni on the classpath?

**Comment by luciangruiaro** [comment]
I think this is related to an older issue I was reporting. Unfortunately at that moment I was not able to try other alternatives, so we postponed the implementation of the feature, but now we are facing this issue again. 

 #https://github.com/luben/zstd-jni/issues/162

**Comment by luben** [comment]
Can you try with the newer versions of zstd-jni?

**Comment by luciangruiaro** [comment]
Just tried with https://mvnrepository.com/artifact/com.github.luben/zstd-jni/1.5.0-4 and still facing the issue.

**Comment by luben** [comment]
It still looks like some mixing of versions. Previously the native library didn't include the version in the file name, the library was named  `/linux/amd64/libzstd-jni.so`. Since https://github.com/luben/zstd-jni/pull/169 the native library is also versioned. It looks like the java code that loads the native library is older (no versioning) but the jar supplies only the versioned lib.

**Comment by luciangruiaro** [comment]
I have solved this issue by implementing these 2 apis: http://ip-api.com/json and https://timezonedb.com/

**Comment by luben** [comment]
@rengaa30, any chance you use some kind of jar minimization/repackaging/relocation? If you do this, don't rename the zstd classes and also make sure to include also the native libraries. Better just exclude the `zstd-jni` from the repackaging.

**Comment by pmallikharjuna-delta** [comment]
@luben
getting this error while trying to write the data as "delta" format with pyspark . we have older version in /usr/lib64/libzstd-jni-1.4.4.so file, but we are trying to use libzstd-jni-1.5.5-4.jar ,then we are getting the following error.
if we downgrade the version then we are getting some of classes not found like "" java.lang.NoClassDefFoundError: com/github/luben/zstd/ZstdOutputStreamNoFinalizer" 
Kindly advice , how can I fix this issue
ERROR:
24/10/02 00:39:50 ERROR MapOutputTrackerMaster: null
java.lang.reflect.InvocationTargetException

Caused by: java.lang.UnsatisfiedLinkError: /tmp/libzstd-jni-1.5.5-42506242103565835660.so: /tmp/libzstd-jni-1.5.5-42506242103565835660.so: failed to map segment from shared object
no zstd-jni-1.5.5-4 in java.library.path
Unsupported OS/arch, cannot find /linux/amd64/libzstd-jni-1.5.5-4.so or load zstd-jni-1.5.5-4 from system libraries. Please try building from source the jar or providing libzstd-jni-1.5.5-4 in your system.
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1860)

**Comment by naveenbussari** [comment]
@luben 
I am also facing the same error while running a pyspark job even though zstd-jni-1.5.6-6.jar exists in the path, LIBRARY_PATH. 

```
24/10/27 04:32:04 ERROR MapOutputTrackerMaster: null
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.apache.spark.io.CompressionCodec$.createCodec(CompressionCodec.scala:87)
	at org.apache.spark.MapOutputTracker$.serializeOutputStatuses(MapOutputTracker.scala:1492)
	at org.apache.spark.ShuffleStatus.$anonfun$serializedMapStatus$2(MapOutputTracker.scala:338)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at org.apache.spark.ShuffleStatus.withWriteLock(MapOutputTracker.scala:77)
	at org.apache.spark.ShuffleStatus.serializedMapStatus(MapOutputTracker.scala:335)
	at org.apache.spark.MapOutputTrackerMaster$MessageLoop.handleStatusMessage(MapOutputTracker.scala:729)
	at org.apache.spark.MapOutputTrackerMaster$MessageLoop.run(MapOutputTracker.scala:746)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.UnsatisfiedLinkError: /tmp/libzstd-jni-1.5.6-61001848644097109181.so: /tmp/libzstd-jni-1.5.6-61001848644097109181.so: failed to map segment from shared object
no zstd-jni-1.5.6-6 in java.library.path: [/opt/spark/jars]
Unsupported OS/arch, cannot find /linux/amd64/libzstd-jni-1.5.6-6.so or load zstd-jni-1.5.6-6 from system libraries. Please try building from source the jar or providing libzstd-jni-1.5.6-6 in your system.
	at java.base/java.lang.ClassLoader.loadLibrary(Unknown Source)
	at java.base/java.lang.Runtime.loadLibrary0(Unknown Source)
```

**Comment by luben** [comment]
@naveenbussari , I think this is another issue. Check you check that /tmp is not mounted with noexec? If that's the case you can specify what directory to use for extracting the native lib by defining property `ZstdTempFolder`

**Comment by naveenbussari** [comment]
Thanks @luben 

/tmp is mounted with noexec. Fixed it by mounting to some other location.
<img width="899" alt="image" src="https://github.com/user-attachments/assets/8dc6720e-2bb5-47ee-8379-a0b187b64c03">
