### ISSUE TITLE
Unsupported OS/arch, cannot find  /linux/armv8l/libzstd-jni-1.5.2-3.so or load zstd-jni-1.5.2-3 from system libraries

### ISSUE THREAD

**Issue by kwind** [luben/zstd-jni#232]
hi luben, I try to use zstd-jni (1.5.2-3) lib in my android project in Android studio IDE, so I import this lib with gradle like:
dependencies {
.....
 implementation "com.github.luben:zstd-jni:1.5.2-3@aar"
 testImplementation "com.github.luben:zstd-jni:1.5.2-3"
.....
}

the following error message:

09-22 15:58:35.062 28334 29896 W System.err: Caused by: java.lang.UnsatisfiedLinkError: BundleClassLoader[/data/user/0/com.eg.android.AlipayGphone/app_plugins/android-sniper-20220922-153246.jar] couldn't find "libzstd-jni-1.5.2-3.so"
09-22 15:58:35.062 28334 29896 W System.err: Unsupported OS/arch, cannot find /linux/armv8l/libzstd-jni-1.5.2-3.so or load zstd-jni-1.5.2-3 from system libraries. Please try building from source the jar or providing libzstd-jni-1.5.2-3 in your system.
09-22 15:58:35.062 28334 29896 W System.err: 	at java.lang.Runtime.loadLibrary0(Runtime.java:1011)
09-22 15:58:35.062 28334 29896 W System.err: 	at java.lang.System.loadLibrary(System.java:1657)
09-22 15:58:35.062 28334 29896 W System.err: 	at com.github.luben.zstd.util.Native.load(Native.java:87)
09-22 15:58:35.063 28334 29896 W System.err: 	at com.github.luben.zstd.util.Native.load(Native.java:55)
09-22 15:58:35.063 28334 29896 W System.err: 	at com.github.luben.zstd.ZstdInputStreamNoFinalizer.<clinit>(ZstdInputStreamNoFinalizer.java:23)
09-22 15:58:35.063 28334 29896 W System.err: 	... 17 more

**Comment by luben** [comment]
This looks something new, in the `aar` we have a build for `arm64-v8a`. Do you know what is `arm64-v8l`? When it was introduced? Is it compatible with `v8a`?

**Comment by luben** [comment]
Hmm, I guess I have to update my Android studio, or mess with the config to enable that target

**Comment by luben** [comment]
Updated my Android studio and NDK to r29 and I don't see option to enable `arm64-v8l`
