### ISSUE TITLE
JVM fatal error when using  Zstd.decompress.

### ISSUE THREAD

**Issue by MsDidin** [luben/zstd-jni#251]
### **java pid error:**
```
Stack: [0x00007f7ca6431000,0x00007f7ca6532000],  sp=0x00007f7ca652f910,  free space=1018k
Native frames: (J=compiled Java code, A=aot compiled Java code, j=interpreted, Vv=VM code, C=native code)
V  [libjvm.so+0x571ad1]  AccessInternal::PostRuntimeDispatch<G1BarrierSet::AccessBarrier<1097812ul, G1BarrierSet>, (AccessInternal::BarrierType)2, 1097812ul>::oop_access_barrier(void*)+0x1
C  [libzstd-jni2823447440483617481.so+0x114d1]  Java_com_github_luben_zstd_Zstd_decompress+0x51

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
j  com.github.luben.zstd.Zstd.decompress([B[B)J+0
j  com.github.luben.zstd.Zstd.decompress([BI)[B+6
```

### **gdb bt command for core dump file:**
```
#0  0x00007f8b318961d7 in raise () from /lib64/libc.so.6
#1  0x00007f8b318978c8 in abort () from /lib64/libc.so.6
#2  0x00007f8b30f9bee5 in os::abort(bool, void*, void const*) () from /usr/java/kona11.0.11/lib/server/libjvm.so
#3  0x00007f8b311b64b9 in VMError::report_and_die(int, char const*, char const*, __va_list_tag*, Thread*, unsigned char*, void*, void*, char const*, int, unsigned long) ()
   from /usr/java/kona11.0.11/lib/server/libjvm.so
#4  0x00007f8b311b6ec1 in VMError::report_and_die(Thread*, unsigned int, unsigned char*, void*, void*, char const*, ...) () from /usr/java/kona11.0.11/lib/server/libjvm.so
#5  0x00007f8b311b6ef1 in VMError::report_and_die(Thread*, unsigned int, unsigned char*, void*, void*) () from /usr/java/kona11.0.11/lib/server/libjvm.so
#6  0x00007f8b30fa72d0 in JVM_handle_linux_signal () from /usr/java/kona11.0.11/lib/server/libjvm.so
#7  0x00007f8b30f99b28 in signalHandler(int, siginfo*, void*) () from /usr/java/kona11.0.11/lib/server/libjvm.so
#8  <signal handler called>
#9  0x00007f8b3093cad1 in AccessInternal::PostRuntimeDispatch<G1BarrierSet::AccessBarrier<1097812ul, G1BarrierSet>, (AccessInternal::BarrierType)2, 1097812ul>::oop_access_barrier(void*) () from /usr/java/kona11.0.11/lib/server/libjvm.so
#10 0x00007f8b30c965da in **jni_GetArrayLength** () from /usr/java/kona11.0.11/lib/server/libjvm.so
```

### I found the crash point in jni implementation code(tag 1.3.7-1)：
```
JNIEXPORT jlong JNICALL Java_com_github_luben_zstd_Zstd_decompress
  (JNIEnv *env, jclass obj, jbyteArray dst, jbyteArray src) {
    size_t size = (size_t)(0-ZSTD_error_memory_allocation);
    jsize dst_size = (*env)->GetArrayLength(env, dst);
    jsize src_size = (*env)->GetArrayLength(env, src);
    void *dst_buff = (*env)->GetPrimitiveArrayCritical(env, dst, NULL);
    if (dst_buff == NULL) goto E1;
    void *src_buff = (*env)->GetPrimitiveArrayCritical(env, src, NULL);
    if (src_buff == NULL) goto E2;
    size = ZSTD_decompress(dst_buff, (size_t) dst_size, src_buff, (size_t) src_size);
    (*env)->ReleasePrimitiveArrayCritical(env, src, src_buff, JNI_ABORT);
E2: (*env)->ReleasePrimitiveArrayCritical(env, dst, dst_buff, 0);
E1: return size;
}
```

Do you have any idea why this crash occurred ? 
And I have noticed that function Java_com_github_luben_zstd_Zstd_decompress is deleted in the latest master version, is there any reason this function not supported ?

**Comment by MsDidin** [comment]
I will close this issue since crash caused by passing null array to native code.
