### ISSUE TITLE
Operation not permitted: UnsatisfiedLinkError with libzstd-jni-1.5.5-1.so

### ISSUE THREAD

**Issue by mayurhpatel91** [luben/zstd-jni#273]
I encountered an issue while running Kafka client, which seems to be related to the loading of the native library libzstd-jni-1.5.5-1.so.
 
```
Caused by: org.apache.kafka.common.KafkaException: java.lang.UnsatisfiedLinkError: /tmp/libso18075650492801527530/libzstd-jni-1.5.5-1.so: Error loading shared library /tmp/libso18075650492801527530/libzstd-jni-1.5.5-1.so: Operation not permitted
	at org.apache.kafka.common.compress.ZstdFactory.wrapForInput(ZstdFactory.java:70)
	at org.apache.kafka.common.record.CompressionType$5.wrapForInput(CompressionType.java:127)
	at org.apache.kafka.common.record.DefaultRecordBatch.recordInputStream(DefaultRecordBatch.java:276)
	at org.apache.kafka.common.record.DefaultRecordBatch.compressedIterator(DefaultRecordBatch.java:280)
	at org.apache.kafka.common.record.DefaultRecordBatch.streamingIterator(DefaultRecordBatch.java:364)
	at org.apache.kafka.clients.consumer.internals.CompletedFetch.nextFetchedRecord(CompletedFetch.java:208)
	at org.apache.kafka.clients.consumer.internals.CompletedFetch.fetchRecords(CompletedFetch.java:255)
	... 72 common frames omitted
Caused by: java.lang.UnsatisfiedLinkError: /tmp/libso18075650492801527530/libzstd-jni-1.5.5-1.so: Error loading shared library /tmp/libso18075650492801527530/libzstd-jni-1.5.5-1.so: Operation not permitted
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(Unknown Source)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(Unknown Source)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(Unknown Source)
	at java.base/java.lang.ClassLoader.loadLibrary(Unknown Source)
	at java.base/java.lang.Runtime.load0(Unknown Source)
	at java.base/java.lang.System.load(Unknown Source)
	at com.github.luben.zstd.util.Native$2.run(Native.java:78)
	at com.github.luben.zstd.util.Native$2.run(Native.java:76)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
```

**Environment Details:**

Kafka Version: kafka-clients:2.8.0
Operating System: linux_amd64
Java Version: OpenJDK 17

**Comment by luben** [comment]
Is your `/tmp` mounted with `noexec` option? This prevents linking the native code.
