### ISSUE TITLE
`apache-commons` fails to find `zstd-jni` on some `jna`/`jna-platform` versions

### ISSUE THREAD

**Issue by ArchangelX360** [luben/zstd-jni#300]
Classpath containing:
- `jna-platform` and `jna` in version `5.7.0`: working
- `jna-platform` and `jna` in version `5.13.0`: failing with
```
Caused by: org.apache.commons.compress.compressors.CompressorException: Zstandard compression is not available. In addition to Apache Commons Compress you need the Zstd JNI library - see https://github.com/luben/zstd-jni
        at org.apache.commons.compress.compressors.CompressorStreamFactory.createCompressorInputStream(CompressorStreamFactory.java:584)
        at org.apache.commons.compress.compressors.CompressorStreamFactory.createCompressorInputStream(CompressorStreamFactory.java:548)
        at fleet.build.fs.ArchiveUtilsKt.extractCompressedTar(ArchiveUtils.kt:61)
        at fleet.build.fs.ArchiveUtilsKt.extractTarZst(ArchiveUtils.kt:28)
        at fleet.build.fs.ArchiveUtilsKt.extractTarZst(ArchiveUtils.kt:19)
        at fleet.build.DownloadJdkTask.execute(DownloadJdkTask.kt:94)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:125)
```

**Comment by ArchangelX360** [comment]
Nevermind, it was not related to `jna` at all. `org.apache.commons:commons-compress` was loaded in an incorrect classloader which did not have [ZSTD](https://github.com/luben/zstd-jni) lib in it. Sorry for the noise.
