### ISSUE TITLE
UnsatisfiedLinkError with "/lib64/libc.so.6: version `GLIBC_2.14' not found ".

### ISSUE THREAD

**Issue by mimineck** [luben/zstd-jni#31]
Hi, 
     When I use 'zstd-jni' in Suse11Sp3x64 or CentOS7x64 , the error described in the title would be throwed.
     Could you fix this problem? Thank you.
Best Regards.

**Comment by jordanhgl** [comment]
I am facing the same problem:

04-10 16:34:16.646 12096-12096/com.example.hangl E/AndroidRuntime: FATAL EXCEPTION: main
                                                                   Process: com.example.hangl, PID: 12096
                                                                   java.lang.UnsatisfiedLinkError: dlopen failed: library "libc.so.6" not found
                                                                       at java.lang.Runtime.load(Runtime.java:332)
                                                                       at java.lang.System.load(System.java:1069)
                                                                       at com.github.luben.zstd.util.Native.load(Native.java:101)
                                                                       at com.github.luben.zstd.Zstd.<clinit>(Zstd.java:12)
                                                                       at com.example.hangl.zstdtest.ZstdTestActivity.onClick(ZstdTestActivity.java:69)
                                                                       at android.view.View.performClick(View.java:5212)
                                                                       at android.view.View$PerformClick.run(View.java:21214)
                                                                       at android.os.Handler.handleCallback(Handler.java:739)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                       at android.os.Looper.loop(Looper.java:148)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:5628)
                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:853)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:737)

I change some code in Native.java, change the way to open so file as input stream, temp file for System.load() created , but load method throw this exception , I try to use zstd-jni.jar in my android project .

**Comment by luben** [comment]
I think it will need separate build for android. Though I have no exposure to the platform.

**Comment by mimineck** [comment]
Thanks a lot, I will build it by myself. But I can't find the jni source(C language) of zstd-jni-1.1.2 , there is no branch of this version. Need your help, thank you.

**Comment by luben** [comment]
I would suggest building the tip of the master, it's the 1.1.4 version and there are not API changes.

If you want to build the 1.1.2 version, you can checkout commit 0a820353c143ba9c3903c7eaeda266ad43d85903 - I should to better job with tagging the releases.
