### ISSUE TITLE
Lack of AIX libs

### ISSUE THREAD

**Issue by andreas-ibm** [luben/zstd-jni#323]
Hello,
i just hit this when trying to load Kafka 3.8.0:
```
java.lang.UnsatisfiedLinkError: Can't load zstd-jni-1.5.6-3
Unsupported OS/arch, cannot find /aix/ppc64/libzstd-jni-1.5.6-3.so or load zstd-jni-1.5.6-3 from system libraries. Please try building from source the jar or providing libzstd-jni-1.5.6-3 in your system.
	at java.base/java.lang.ClassLoader.loadLibrary(Unknown Source)
	at java.base/java.lang.System.loadLibrary(Unknown Source)
	at com.github.luben.zstd.util.Native$1.run(Native.java:70)
	at com.github.luben.zstd.util.Native$1.run(Native.java:68)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at com.github.luben.zstd.util.Native.loadLibrary(Native.java:68)
	at com.github.luben.zstd.util.Native.load(Native.java:118)
	at com.github.luben.zstd.util.Native.load(Native.java:86)
	at com.github.luben.zstd.Zstd.<clinit>(Zstd.java:12)
	at org.apache.kafka.common.compress.ZstdCompression.<clinit>(ZstdCompression.java:41)
	at org.apache.kafka.storage.internals.log.LogConfig.<clinit>(LogConfig.java:251)
	at kafka.server.KafkaConfig$.<clinit>(KafkaConfig.scala:308)
	at kafka.Kafka$.buildServer(Kafka.scala:71)
	at kafka.Kafka$.main(Kafka.scala:90)
	at kafka.Kafka.main(Kafka.scala)
```
I'm in the process of cloning your sources on to an AIX box to try to build it myself, but thought I'd ask if there was a particular reason it's dropped?

**Comment by luben** [comment]
After some point I was not able to build it anymore on the in the gcc compile farm box. Not sure what exactly was change but we started getting errors at compile.  It may not be change on the AIX box but due to sources, as I disabled it when releasing 1.5.0-1 that imports the upstream C sources.

**Comment by andreas-ibm** [comment]
alas I've locked myself out of our main dev box, and on our test box I get:
```
zstd-jni/sbt-java-module-info$./sbt publishLocal
[info] [launcher] getting org.scala-sbt sbt 1.9.6  (this may take some time)...
[error] [launcher] java.lang.ExceptionInInitializerError
[error] [launcher] could not retrieve sbt 1.9.6
```
is there an obvious fix to that?

If I can figure out what's wrong with the AIX compile, would you be willing to re-enable it?

**Comment by andreas-ibm** [comment]
I can't get sbt working at all on AIX, I'm giving up for the day!

**Comment by luben** [comment]
I was using https://github.com/luben/zstd-jni/blob/master/make_so.sh to build the shared object, never were able to run sbt on AIX.

**Comment by luben** [comment]
Actually better start with https://github.com/luben/zstd-jni/blob/v1.5.0-1/make_so.sh#L21-L34 - this is when we disabled the AIX compilation, later we removed the build script

**Comment by luben** [comment]
I was able to build it again on the AIX host and it's included in the just released v1.5.6-5 . Please test it.

**Comment by andreas-ibm** [comment]
You're a totally awesome legend! It works beautifully!

**Comment by luben** [comment]
Thanks for confirming! Will add it to the supported configurations in the README.

The issue was something with the 1.5.0 upstream source code, not sure why but it failed with some undefined variables. It was fixed upstream since then.
