### ISSUE TITLE
Exception in thread "pool-3-thread-1" java.lang.UnsatisfiedLinkError: no zstd-jni-1.5.6-7 in java.library.path 

### ISSUE THREAD

**Issue by Amzlov123** [luben/zstd-jni#330]
I am facing this issue when trying to run unit-tests within Android Studio:

```
Exception in thread "pool-3-thread-1" java.lang.UnsatisfiedLinkError: no zstd-jni-1.5.6-7 in java.library.path: /Users/<user>/Library/Java/Extensions:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java:.
Unsupported OS/arch, cannot find /darwin/aarch64/libzstd-jni-1.5.6-7.dylib or load zstd-jni-1.5.6-7 from system libraries. Please try building from source the jar or providing libzstd-jni-1.5.6-7 in your system.
	at java.base/java.lang.ClassLoader.loadLibrary(Unknown Source)
	at java.base/java.lang.Runtime.loadLibrary0(Unknown Source)
	at java.base/java.lang.System.loadLibrary(Unknown Source)
	at com.github.luben.zstd.util.Native$1.run(Native.java:71)
	at com.github.luben.zstd.util.Native$1.run(Native.java:69)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at com.github.luben.zstd.util.Native.loadLibrary(Native.java:69)
	at com.github.luben.zstd.util.Native.load(Native.java:124)
	at com.github.luben.zstd.util.Native.load(Native.java:89)
	at com.github.luben.zstd.ZstdInputStreamNoFinalizer.<clinit>(ZstdInputStreamNoFinalizer.java:23)
	at com.github.luben.zstd.ZstdInputStream.<init>(ZstdInputStream.java:24)
```

**Comment by Amzlov123** [comment]
I forgot to include the testImplementation as part of my build.gradle dependency and this addressed my issue:

```
dependencies {
    implementation "com.github.luben:zstd-jni:VERSION@aar"
    testImplementation "com.github.luben:zstd-jni:VERSION"
} 
```
