### ISSUE TITLE
The library nddsjava.dll could not be loaded by Windows.

### ISSUE THREAD

**Issue by vinittcs** [luben/zstd-jni#42]
Hi I am trying to run a jar which uses RTI connext dependencies . When I run it I get following stack trace :
java.lang.UnsatisfiedLinkError: C:\Users\477047\Downloads\configService\nddsjava.dll: Can't find dependent libraries
        at java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.lang.ClassLoader.loadLibrary0(Unknown Source)
        at java.lang.ClassLoader.loadLibrary(Unknown Source)
        at java.lang.Runtime.loadLibrary0(Unknown Source)
        at java.lang.System.loadLibrary(Unknown Source)
        at com.rti.dds.util.NativeInterface.loadNativeLibrary(Unknown Source)
        at com.rti.dds.util.NativeInterface.loadNativeLibraries(Unknown Source)
        at com.rti.ndds.config.Logger.<clinit>(Unknown Source)
        at com.ge.hc.lcs.axonenet.logging.LoggerFactory.configureDDSLogger(LoggerFactory.java:179)
        at om.ge.hc.lcs.axonenet.logging.LoggerFactory.getLogListenerWorkerThread(LoggerFactory.java:113)
        at com.ge.hc.lcs.axone.configservice.ConfigServiceController.initializeLogger(ConfigServiceController.java:285)
        at com.ge.hc.lcs.axone.configservice.ConfigServiceController.<init>(ConfigServiceController.java:100)
        at com.ge.hc.lcs.axone.configservice.ConfigServiceController.createConfigServiceController(ConfigServiceController.java:
        at com.ge.hc.lcs.axone.configservice.ConfigServiceMain.start(ConfigServiceMain.java:263)
        at com.ge.hc.lcs.axone.configservice.ConfigServiceMain.main(ConfigServiceMain.java:125)

I have all the DLL in the folder where I am executing this JAR  the java version is JDK1.8

**Comment by luben** [comment]
I am not sure what "nddsjava.dll" is about. I don't have access to windows for testing it.

BTW, in the stack trace I don't see anything related to zstd-jni. Are you sure it's cause by it?

**Comment by luben** [comment]
closing as I don't see how it is related with  zstd-jni - it's not even in the stack trace
