### ISSUE TITLE
Launching reader and writer with "closeFrameOnFlush=true" and "continuous=true" causes "java.io.Exception: Compression error: Context should be init first"

### ISSUE THREAD

**Issue by stmlange** [luben/zstd-jni#52]
Again I fear this might be another edge-case where I assume that this might even be supported in the native library (or caused by shared stuff between reader and writer). In general what I'm currently testing if it is possible to launch reader and writer in parallel by making use of the  "closeFrameOnFlush=true" and "continuous=true"  (see full code below). However it seems that from the java side the frame is correctly closed and thus invokes a flushStream in the native library (https://github.com/luben/zstd-jni/blob/master/src/main/java/com/github/luben/zstd/ZstdOutputStream.java#L114). This then somehow triggers a "Context should be init first" exception.

Open Question: Is this (even) supported? Logic wise the reader should read a full frame (since the writer invoked flush and should have caused the frame to close). 

### Stacktrace:
```
org.gradle.CompressionTest > runTest FAILED
    java.io.IOException: Compression error: Context should be init first
        at com.github.luben.zstd.ZstdOutputStream.flush(ZstdOutputStream.java:116)
        at sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:297)
        at sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:141)
        at java.io.OutputStreamWriter.flush(OutputStreamWriter.java:229)
        at java.io.BufferedWriter.flush(BufferedWriter.java:254)
        at org.gradle.CompressionTest.runTest(CompressionTest.java:53)
```

### Steps to Reproduce 
```java
import java.io.*;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;

import com.github.luben.zstd.ZstdInputStream;
import com.github.luben.zstd.ZstdOutputStream;

import org.junit.Test;

import static org.junit.Assert.*;

public class CompressionTest {
    private static final int ZSTD_CLEVEL_DEFAULT = 3;

    @Test
    public void runTest() throws Throwable {
        try {
            final File compressedFile = createTempFile("random_compressed");
            final File uncompressed   = createTempFile("random_extracted");

            // create writer
            final BufferedWriter writer = new BufferedWriter(
                    new OutputStreamWriter(new ZstdOutputStream(
                            Files.newOutputStream(compressedFile.toPath()),
                            ZSTD_CLEVEL_DEFAULT, true),
                            StandardCharsets.UTF_8));
            // create reader
            final BufferedReader reader = new BufferedReader(
                    new InputStreamReader(
                            new ZstdInputStream(
                                Files.newInputStream(compressedFile.toPath())
                            ).setContinuous(true),
                            StandardCharsets.UTF_8));

            // feed content into writer
            for (int i = 0; i < 20; i++) {
                writer.write(i + System.lineSeparator());
            }
            // flush to cause a new frame
            writer.flush();

            // read content (should be possible since frame is closed?)
            for (int i = 0; i < 20; i++) {
                String line;
                while ((line = reader.readLine()) != null) {
                    System.out.println(line);
                }
            }

            // close
            writer.flush(); // flush or close causes an Exception
            writer.close();
            reader.close();
        } catch (final Throwable t) {
            // t.printStackTrace();
            throw t;
        }
    }

    private File createTempFile(final String prefix) throws IOException {
        final File tempFile = File.createTempFile(prefix, ".tmp");
        tempFile.deleteOnExit();
        return tempFile;
    }
}
```

**Comment by luben** [comment]
Thanks again for reporting it. I see where is the problem. I will push in a minute to the repo and will release later today.

**Comment by stmlange** [comment]
Hi luben once again thank you for the quick fix!
Sorry to find all the corner cases :-P

Just out of curiosity have you pushed the new version to maven central? It doesn't seem to be available currently (maybe stuck in the deployment pipeline)

**Comment by luben** [comment]
Hi, yes, I forgot to push it yesterday. I will push it later today (my PGP key is offline).

**Comment by luben** [comment]
On its way to maven.

**Comment by stmlange** [comment]
Hi,
thanks for tacking care of this so quickly.
I can confirm that the new version is now available and this is working fine with `com.github.luben:zstd-jni:1.3.3-3`
