### ISSUE TITLE
 Corrupted block detected

### ISSUE THREAD

**Issue by learn2Pro** [luben/zstd-jni#81]
java.lang.RuntimeException: Corrupted block detected +details
java.lang.RuntimeException: Corrupted block detected
	at com.github.luben.zstd.Zstd.decompress(Zstd.java:743)
	at com.alipay.sharkgraph.storage.compress.impl.ZstdCompress.decompress(ZstdCompress.scala:32)
	at com.alipay.sharkgraph.storage.util.GraphBlockByteParseUtil$.getBlock2ByteBuffer(GraphBlockByteParseUtil.scala:103)
	at com.alipay.sharkgraph.storage.util.vertex.GraphVertexBlockIoUtil$.readBlockVertexRoutesWithId(GraphVertexBlockIoUtil.scala:239)
	at

**Comment by luben** [comment]
Looks like corrupted blocks. Which version you are using? Are you able to decompress the input using the zstd CLI.

**Comment by learn2Pro** [comment]
<dependency>
                <groupId>com.github.luben</groupId>
                <artifactId>zstd-jni</artifactId>
                <version>1.3.4-10</version>
            </dependency>

**Comment by learn2Pro** [comment]
i did not try the zstd cli

**Comment by luben** [comment]
Yes, please try the CLI. Currently, it's telling the input data is corrupted - the message comes from the C library.

**Comment by learn2Pro** [comment]
ok,thanks
