### ISSUE TITLE
Fails to work on Android 

### ISSUE THREAD

**Issue by naveedhassan913** [luben/zstd-jni#85]
Here is logcat error 
It occured when using 
```
Zstd.compress(name.getBytes()
```

`Caused by: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/hahmap.maker-1/base.apk"],nativeLibraryDirectories=[/data/app/hahmap.maker-1/lib/arm64, /data/app/hahmap.maker-1/base.apk!/lib/arm64-v8a, /vendor/lib64, /system/lib64]]] couldn't find "libzstd-jni.so"
Unsupported OS/arch, cannot find /linux/aarch64/libzstd-jni.so or load zstd-jni from system libraries. Please try building from source the jar or providing libzstd-jni in you system.
	at java.lang.Runtime.loadLibrary(Runtime.java:367)
	at java.lang.System.loadLibrary(System.java:1076)
	at com.github.luben.zstd.util.Native.load(Native.java:108)
	at com.github.luben.zstd.util.Native.load(Native.java:60)
	at com.github.luben.zstd.Zstd.<clinit>(Zstd.java:11)
	at hahmap.maker.BohtKam.doInBackground(BohtKam.java:122)
	at hahmap.maker.BohtKam.doInBackground(BohtKam.java)
	at android.os.AsyncTask$2.call(AsyncTask.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	... 4 more
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/hahmap.maker-1/base.apk"],nativeLibraryDirectories=[/data/app/hahmap.maker-1/lib/arm64, /data/app/hahmap.maker-1/base.apk!/lib/arm64-v8a, /vendor/lib64, /system/lib64]]] couldn't find "libzstd-jni.so"
Unsupported OS/arch, cannot find /linux/aarch64/libzstd-jni.so or load zstd-jni from system libraries. Please try building from source the jar or providing libzstd-jni in you system.
	at java.lang.Runtime.loadLibrary(Runtime.java:367)
	at java.lang.System.loadLibrary(System.java:1076)
	at com.github.luben.zstd.util.Native.load(Native.java:108)
	at com.github.luben.zstd.util.Native.load(Native.java:60)
	at com.github.luben.zstd.Zstd.<clinit>(Zstd.java:11)
	at hahmap.maker.BohtKam.doInBackground(BohtKam.java:122)
	at hahmap.maker.BohtKam.doInBackground(BohtKam.java)
	at android.os.AsyncTask$2.call(AsyncTask.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)` 

_Sent from my HOT 4 PRO using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by naveedhassan913** [comment]
Im using this version 1.3.3-3

**Comment by naveedhassan913** [comment]
Im using this version 1.3.3-3

**Comment by naveedhassan913** [comment]
zstd-jni:1.3.8-1

**Comment by naveedhassan913** [comment]
zstd-jni:1.3.8-1

**Comment by luben** [comment]
Try

- adding maven central registry:
```
allprojects {
    repositories {
        jcenter()
        mavenCentral()
    }
}
```

and then adding the dependency the usual way:

https://developer.android.com/studio/build/dependencies

**Comment by naveedhassan913** [comment]
Well the issue still exist. With same above error.

**Comment by luben** [comment]
I think you are doing something wrong but without seeing the source I can't help much. Here is a project that I just created to show how to use zstd-jni in Android app:

https://github.com/luben/ZstdAndroidExample

Look at the 2nd and 3rd commit there, the rest is boilerplate.
